import type { DesignDoc } from "./design";

export const WEBSITE_SHOWCASES: {
  id: string;
  title: string;
  tagline: string;
  prompt: string;
  doc: DesignDoc;
}[] = [
  {
    id: "shipper-cloud",
    title: "Shipper Studio",
    tagline: "Build, Compose, and Ship Websites in Seconds.",
    prompt: "Modern developer studio and website builder with live terminal deployment, micro-animations, and bento grid layout in pure light theme",
    doc: {
      format: "website",
      name: "Shipper Studio",
      tagline: "Build, Compose, and Ship Websites in Seconds.",
      theme: {
        bg: "#FFFFFF",
        fg: "#0F172A",
        muted: "#64748B",
        line: "#E2E8F0",
        accent: "#0284C7",
        accentFg: "#FFFFFF",
        surface: "#F8FAFC",
        fontDisplay: "sans",
        radius: "16px",
        mood: "cyber",
        heroVisual: "bento",
      },
      nav: {
        logo: "SHIPPER.NOW",
        links: ["Platform", "Templates", "Showcase", "Pricing", "Docs"],
        cta: "Start Free",
      },
      sections: [
        {
          kind: "terminal_hero",
          kicker: "v3.0 Next-Gen Builder",
          headline: "Turn any idea or URL into a production website.",
          sub: "Inspect visual DNA, extract layout rhythm, and compile responsive Tailwind & React code in under 30 seconds.",
          cta: "Compose Website Free",
          secondary: "View Live Demo",
          command: "npx shipper init my-site --template modern",
          logs: [
            "✓ Extracted typography & layout hierarchy",
            "✓ Rendered responsive 16:9 hero & bento grid",
            "✓ Production Tailwind CSS ready to export",
          ],
        },
        {
          kind: "tech_bento",
          title: "Engineered for speed, aesthetics, and clean code.",
          cards: [
            {
              title: "Instant URL Cloning",
              subtitle: "Paste any link to analyze design rhythm and recreate tailored components.",
              tag: "Intelligence",
              highlight: "< 10s",
            },
            {
              title: "Export Ready Code",
              subtitle: "Clean semantic HTML, Tailwind CSS, and standalone React modules ready to deploy.",
              tag: "Production",
              highlight: "Zero Lock-in",
            },
            {
              title: "Micro-Interaction Engine",
              subtitle: "Pre-configured spring physics, glowing gradients, and fluid hover states.",
              tag: "Visuals",
              highlight: "60 FPS",
            },
          ],
        },
        {
          kind: "architecture_flow",
          kicker: "Pipeline",
          title: "From Prompt to Shipped Code",
          steps: [
            { title: "Prompt / URL Ingest", desc: "Extract typography, spacing, and brand palette tokens.", metric: "2ms" },
            { title: "Agentic Layout Synthesis", desc: "Compose grid blocks, responsive viewports, and navigation.", metric: "99.8%" },
            { title: "Production Code Bundling", desc: "Compile standalone HTML/Tailwind bundles with zero dependencies.", metric: "Instant" },
          ],
        },
      ],
    },
  },
  {
    id: "aureli-monograph",
    title: "Aureli Architekten",
    tagline: "Architecture of silence and enduring weight.",
    prompt: "Swiss architecture atelier monograph with alpine glass pavilions, concrete residences, and editorial type",
    doc: {
      format: "website",
      name: "Aureli Architekten",
      tagline: "Architecture of silence and enduring weight.",
      theme: {
        bg: "#FAF9F6",
        fg: "#171411",
        muted: "#6B655C",
        line: "#E6E1D8",
        accent: "#B83B26",
        accentFg: "#FFFFFF",
        surface: "#FFFFFF",
        fontDisplay: "serif",
        radius: "6px",
        mood: "swiss",
        heroVisual: "architecture",
      },
      nav: {
        logo: "AURELI ATELIER",
        links: ["Monographs", "Philosophy", "Selected Works", "Archive"],
        cta: "Monograph IX",
      },
      sections: [
        {
          kind: "hero",
          layout: "editorial-cover",
          kicker: "Zurich · Milano · Tokyo // Est. 2014",
          meta: "Volume IX · Autumn Edition",
          headline: "Architecture of silence and enduring weight.",
          sub: "Rigorous alpine glass pavilions, monolithic site-cast residences, and spatial restorations designed in dialogue with light.",
          cta: "Explore Selected Works",
          secondary: "Atelier Philosophy",
        },
        {
          kind: "stats",
          items: [
            { value: "38", label: "Built Monographs" },
            { value: "04", label: "Alpine Cantons" },
            { value: "12", label: "International Awards" },
            { value: "100%", label: "Site-Cast Concrete" },
          ],
        },
        {
          kind: "gallery",
          title: "Selected Architecture 2022—2026",
          subtitle: "Rigorous alpine pavilions and monolithic stone residences.",
          layout: "grid-3",
          items: [
            { title: "Haus am Rigi", tag: "Alpine Glass Pavilion", meta: "Küssnacht · 2024" },
            { title: "Gstaad Library & Archive", tag: "Civic Monograph", meta: "Bernese Oberland · 2025" },
            { title: "Engadin Valley Stone Residence", tag: "Residential Cantilever", meta: "Graubünden · 2026" },
          ],
        },
      ],
    },
  },
  {
    id: "lumen-creative",
    title: "Lumen Studio",
    tagline: "We shape culture through precision and chaos.",
    prompt: "Contemporary art direction and spatial brand studio homepage with bold headlines and editorial monographs",
    doc: {
      format: "website",
      name: "Lumen Studio",
      tagline: "We shape culture through precision and chaos.",
      theme: {
        bg: "#FBFBFA",
        fg: "#111827",
        muted: "#6B7280",
        line: "#E5E7EB",
        accent: "#DC2626",
        accentFg: "#FFFFFF",
        surface: "#FFFFFF",
        fontDisplay: "sans",
        radius: "8px",
        mood: "editorial",
        heroVisual: "editorial",
      },
      nav: {
        logo: "LUMEN / CREATIVE",
        links: ["Work", "Direction", "Culture Desk", "Journal"],
        cta: "Book a Project",
      },
      sections: [
        {
          kind: "hero",
          layout: "editorial-cover",
          kicker: "Art Direction & Global Identity Systems",
          meta: "London · Paris · New York",
          headline: "We shape culture through precision and spatial rhythm.",
          sub: "Campaign directions, editorial monographs, and digital identities for global brands that refuse corporate noise.",
          cta: "View Selected Work",
          secondary: "Studio Credo",
        },
        {
          kind: "gallery",
          title: "Campaign Directions",
          subtitle: "Recent identities, editorial books, and immersive brand stages.",
          layout: "grid-3",
          items: [
            { title: "Futura 2026 Identity", tag: "Global Campaign", meta: "Nike Art Direction" },
            { title: "Quiet Luxury Autumn", tag: "Editorial Lookbook", meta: "Lumen Paris" },
            { title: "Spatial Material Monograph", tag: "Fashion & Architecture", meta: "London" },
          ],
        },
      ],
    },
  },
  {
    id: "quill-writing",
    title: "Quill App",
    tagline: "Software that stays out of the novelist's way.",
    prompt: "Clean literary writing studio homepage with chapter maps, paper aesthetics, and focused typography",
    doc: {
      format: "website",
      name: "Quill Writing Studio",
      tagline: "A writing room that doesn't look like software.",
      theme: {
        bg: "#F7F6F2",
        fg: "#1F2937",
        muted: "#6B7280",
        line: "#E5E1D8",
        accent: "#2563EB",
        accentFg: "#FFFFFF",
        surface: "#FFFFFF",
        fontDisplay: "serif",
        radius: "16px",
        mood: "warm",
        heroVisual: "product",
      },
      nav: {
        logo: "QUILL",
        links: ["Manuscripts", "Chapter Maps", "Typography", "Pricing"],
        cta: "Start Manuscript",
      },
      sections: [
        {
          kind: "hero",
          layout: "split",
          kicker: "Crafted for Novelists & Essayists",
          headline: "Software that stays completely out of the way.",
          sub: "A calm digital writing room with non-destructive versioning, chapter maps, and pages that feel like heavy Japanese vellum.",
          cta: "Open Editor Free",
          secondary: "Sample Chapter",
          visual: "product",
        },
        {
          kind: "stats",
          items: [
            { value: "48k", label: "Published Chapters" },
            { value: "2.4M", label: "Words Preserved" },
            { value: "100%", label: "Offline First" },
            { value: "0", label: "Telemetry & Distractions" },
          ],
        },
        {
          kind: "features",
          layout: "cards",
          title: "Composed for deep, uninterrupted thought.",
          items: [
            { title: "Chapter Canvas", body: "Arrange scenes and narrative threads along a spatial horizontal timeline." },
            { title: "Vellum Typesetting", body: "Custom serif type foundry metrics tuned specifically for long-form reading." },
            { title: "Local Git Sync", body: "Your files stay strictly on your device in plain Markdown and LaTeX." },
          ],
        },
      ],
    },
  },
  {
    id: "sentinel-security",
    title: "Sentinel Cloud",
    tagline: "Autonomous edge security that never sleeps.",
    prompt: "Next-gen zero-trust cloud infrastructure homepage with live attack telemetry and edge isolation",
    doc: {
      format: "website",
      name: "Sentinel Mesh",
      tagline: "Security that never sleeps across 42 global regions.",
      theme: {
        bg: "#FFFFFF",
        fg: "#0F172A",
        muted: "#475569",
        line: "#E2E8F0",
        accent: "#0D9488",
        accentFg: "#FFFFFF",
        surface: "#F8FAFC",
        fontDisplay: "sans",
        radius: "16px",
        mood: "cyber",
        heroVisual: "bento",
      },
      nav: {
        logo: "SENTINEL",
        links: ["Mesh", "Edge Runtime", "Threat Graph", "Compliance", "Docs"],
        cta: "Deploy Sentinel",
      },
      sections: [
        {
          kind: "terminal_hero",
          kicker: "Autonomous Edge Shield",
          headline: "Zero-trust edge security across every region.",
          sub: "Live threat mitigation, sub-millisecond edge isolation, and automated telemetry compliance running quietly across your stack.",
          cta: "Protect Your Cluster",
          secondary: "View Threat Graph",
          command: "sentinel mesh --attach-vpc prod-us-east",
          logs: [
            "✓ Edge firewall synced across 42 regions",
            "✓ Sub-millisecond packet inspection active",
            "✓ Zero anomaly drift detected",
          ],
        },
        {
          kind: "tech_bento",
          title: "Telemetry and protection running at wire speed.",
          cards: [
            { title: "Wire-Speed Filtering", subtitle: "Inspect eBPF network packets with under 1.2ms added overhead.", tag: "Infra", highlight: "1.2ms P99" },
            { title: "Autonomous Isolation", subtitle: "Compromised micro-VMs are severed before lateral movement can start.", tag: "Zero-Trust", highlight: "100% Sealed" },
            { title: "SOC2 & FedRAMP Ready", subtitle: "Audit-ready access logs and encrypted key rotation with zero manual steps.", tag: "Compliance", highlight: "Continuous" },
          ],
        },
      ],
    },
  },
  {
    id: "salt-hotel",
    title: "Salt Lisbon",
    tagline: "Stay somewhere that remembers you.",
    prompt: "Quiet coastal hotel and dining house website with tiled floors, ocean desks, and curated dining",
    doc: {
      format: "website",
      name: "Salt Lisbon",
      tagline: "A hotel that keeps the windows open.",
      theme: {
        bg: "#F8FAF9",
        fg: "#132E35",
        muted: "#5B757C",
        line: "#DDE7E6",
        accent: "#1F6A70",
        accentFg: "#FFFFFF",
        surface: "#FFFFFF",
        fontDisplay: "serif",
        radius: "18px",
        mood: "coastal",
        heroVisual: "gradient",
      },
      nav: {
        logo: "SALT LISBON",
        links: ["Rooms", "Dining Table", "Harbor", "Philosophy"],
        cta: "Reserve Room",
      },
      sections: [
        {
          kind: "hero",
          layout: "split",
          kicker: "Lisbon Coast · Est. 2018",
          headline: "Stay somewhere that remembers you.",
          sub: "Tiled floors, long lunches, a desk that faces the morning water, and shutters that actually work.",
          cta: "Explore Rooms",
          secondary: "The Table",
          visual: "gradient",
        },
        {
          kind: "features",
          layout: "minimal-cols",
          title: "Salt air, tiled floors, and slow afternoons.",
          items: [
            { title: "Eleven Rooms", body: "All facing the open Atlantic with natural linen sheets and handmade ceramic water carafes." },
            { title: "The Dining Table", body: "Long lunches until sundown. Fresh catch straight from the morning Cascais market boat." },
            { title: "The Harbor Walk", body: "A five-minute quiet walk along stone cliffs without tourists or tour buses." },
          ],
        },
      ],
    },
  },
];
